/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Euler;

/**
* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

public class Two2 {

	public static int fibonacciEvenSum() {
		int prev0 = 0;
		int prev1 = 1;
		int current = prev0 + prev1;
		int sum = 0;
		while (current < 4000000) {
			if (current % 2 == 0) {
				sum += current;
			}
			prev0 = prev1;
			prev1 = current;
			current = prev0 + prev1;
		}		
		return sum;
	}    
 
        public static void main(String[] args) {
            System.out.println(fibonacciEvenSum());
    }
}
